defmodule Sentry.IssueDetailed do
  @moduledoc """
  Provides struct and type for a IssueDetailed
  """

  @type t :: %__MODULE__{
          activity: [Sentry.IssueDetailedActivity.t()],
          annotations: [String.t()],
          assignedTo: map | nil,
          count: String.t(),
          culprit: String.t(),
          firstRelease: Sentry.IssueDetailedFirstRelease.t() | nil,
          firstSeen: String.t(),
          hasSeen: boolean,
          id: String.t(),
          isBookmarked: boolean,
          isPublic: boolean,
          isSubscribed: boolean,
          lastRelease: map | nil,
          lastSeen: String.t(),
          level: String.t(),
          logger: String.t() | nil,
          metadata: Sentry.IssueDetailedMetadata.t(),
          numComments: integer,
          participants: [map],
          permalink: String.t(),
          pluginActions: [[String.t()]],
          pluginContexts: [String.t()],
          pluginIssues: [map],
          project: Sentry.IssueDetailedProject.t(),
          seenBy: [map],
          shareId: String.t() | nil,
          shortId: String.t(),
          stats: Sentry.IssueDetailedStats.t(),
          status: String.t(),
          statusDetails: map,
          subscriptionDetails: map | nil,
          tags: [map],
          title: String.t(),
          type: String.t(),
          userCount: integer,
          userReportCount: integer
        }

  defstruct [
    :activity,
    :annotations,
    :assignedTo,
    :count,
    :culprit,
    :firstRelease,
    :firstSeen,
    :hasSeen,
    :id,
    :isBookmarked,
    :isPublic,
    :isSubscribed,
    :lastRelease,
    :lastSeen,
    :level,
    :logger,
    :metadata,
    :numComments,
    :participants,
    :permalink,
    :pluginActions,
    :pluginContexts,
    :pluginIssues,
    :project,
    :seenBy,
    :shareId,
    :shortId,
    :stats,
    :status,
    :statusDetails,
    :subscriptionDetails,
    :tags,
    :title,
    :type,
    :userCount,
    :userReportCount
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      activity: [{Sentry.IssueDetailedActivity, :t}],
      annotations: [:string],
      assignedTo: :map,
      count: :string,
      culprit: :string,
      firstRelease: {Sentry.IssueDetailedFirstRelease, :t},
      firstSeen: :string,
      hasSeen: :boolean,
      id: :string,
      isBookmarked: :boolean,
      isPublic: :boolean,
      isSubscribed: :boolean,
      lastRelease: :map,
      lastSeen: :string,
      level: :string,
      logger: :string,
      metadata: {Sentry.IssueDetailedMetadata, :t},
      numComments: :integer,
      participants: [:map],
      permalink: :string,
      pluginActions: [[:string]],
      pluginContexts: [:string],
      pluginIssues: [:map],
      project: {Sentry.IssueDetailedProject, :t},
      seenBy: [:map],
      shareId: :string,
      shortId: :string,
      stats: {Sentry.IssueDetailedStats, :t},
      status: {:enum, ["resolved", "unresolved", "ignored"]},
      statusDetails: :map,
      subscriptionDetails: :map,
      tags: [:map],
      title: :string,
      type: :string,
      userCount: :integer,
      userReportCount: :integer
    ]
  end
end
