defmodule IssueDetailed do
  @moduledoc """
  Provides struct and type for a IssueDetailed
  """

  @type t :: %__MODULE__{
          activity: [IssueDetailedActivity.t()],
          annotations: [String.t()],
          assignedTo: map | nil,
          count: String.t(),
          culprit: String.t(),
          firstRelease: IssueDetailedFirstRelease.t() | nil,
          firstSeen: String.t(),
          hasSeen: boolean,
          id: String.t(),
          isBookmarked: boolean,
          isPublic: boolean,
          isSubscribed: boolean,
          lastRelease: map | nil,
          lastSeen: String.t(),
          level: String.t(),
          logger: String.t() | nil,
          metadata: IssueDetailedMetadata.t(),
          numComments: integer,
          participants: [map],
          permalink: String.t(),
          pluginActions: [[String.t()]],
          pluginContexts: [String.t()],
          pluginIssues: [map],
          project: IssueDetailedProject.t(),
          seenBy: [map],
          shareId: String.t() | nil,
          shortId: String.t(),
          stats: IssueDetailedStats.t(),
          status: String.t(),
          statusDetails: map,
          subscriptionDetails: map | nil,
          tags: [map],
          title: String.t(),
          type: String.t(),
          userCount: integer,
          userReportCount: integer
        }

  defstruct [
    :activity,
    :annotations,
    :assignedTo,
    :count,
    :culprit,
    :firstRelease,
    :firstSeen,
    :hasSeen,
    :id,
    :isBookmarked,
    :isPublic,
    :isSubscribed,
    :lastRelease,
    :lastSeen,
    :level,
    :logger,
    :metadata,
    :numComments,
    :participants,
    :permalink,
    :pluginActions,
    :pluginContexts,
    :pluginIssues,
    :project,
    :seenBy,
    :shareId,
    :shortId,
    :stats,
    :status,
    :statusDetails,
    :subscriptionDetails,
    :tags,
    :title,
    :type,
    :userCount,
    :userReportCount
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      activity: [{IssueDetailedActivity, :t}],
      annotations: [string: :generic],
      assignedTo: :map,
      count: {:string, :generic},
      culprit: {:string, :generic},
      firstRelease: {IssueDetailedFirstRelease, :t},
      firstSeen: {:string, :generic},
      hasSeen: :boolean,
      id: {:string, :generic},
      isBookmarked: :boolean,
      isPublic: :boolean,
      isSubscribed: :boolean,
      lastRelease: :map,
      lastSeen: {:string, :generic},
      level: {:string, :generic},
      logger: {:string, :generic},
      metadata: {IssueDetailedMetadata, :t},
      numComments: :integer,
      participants: [:map],
      permalink: {:string, :generic},
      pluginActions: [[string: :generic]],
      pluginContexts: [string: :generic],
      pluginIssues: [:map],
      project: {IssueDetailedProject, :t},
      seenBy: [:map],
      shareId: {:string, :generic},
      shortId: {:string, :generic},
      stats: {IssueDetailedStats, :t},
      status: {:enum, ["resolved", "unresolved", "ignored"]},
      statusDetails: :map,
      subscriptionDetails: :map,
      tags: [:map],
      title: {:string, :generic},
      type: {:string, :generic},
      userCount: :integer,
      userReportCount: :integer
    ]
  end
end
