defmodule Discord.GuildResponse do
  @moduledoc """
  Provides struct and type for a GuildResponse
  """

  @type t :: %__MODULE__{
          afk_channel_id: String.t() | nil,
          afk_timeout: integer,
          application_id: String.t() | nil,
          banner: String.t() | nil,
          default_message_notifications: integer,
          description: String.t() | nil,
          discovery_splash: String.t() | nil,
          emojis: [Discord.EmojiResponse.t()],
          explicit_content_filter: integer,
          features: [String.t()],
          home_header: String.t() | nil,
          icon: String.t() | nil,
          id: String.t(),
          max_members: integer | nil,
          max_presences: integer | nil,
          max_stage_video_channel_users: integer | nil,
          max_video_channel_users: integer | nil,
          mfa_level: integer,
          name: String.t(),
          nsfw: boolean,
          nsfw_level: integer,
          owner_id: String.t(),
          preferred_locale: String.t(),
          premium_progress_bar_enabled: boolean,
          premium_subscription_count: integer,
          premium_tier: integer,
          public_updates_channel_id: String.t() | nil,
          region: String.t(),
          roles: [Discord.GuildRoleResponse.t()],
          rules_channel_id: String.t() | nil,
          safety_alerts_channel_id: String.t() | nil,
          splash: String.t() | nil,
          stickers: [Discord.GuildStickerResponse.t()],
          system_channel_flags: integer,
          system_channel_id: String.t() | nil,
          vanity_url_code: String.t() | nil,
          verification_level: integer,
          widget_channel_id: String.t() | nil,
          widget_enabled: boolean
        }

  defstruct [
    :afk_channel_id,
    :afk_timeout,
    :application_id,
    :banner,
    :default_message_notifications,
    :description,
    :discovery_splash,
    :emojis,
    :explicit_content_filter,
    :features,
    :home_header,
    :icon,
    :id,
    :max_members,
    :max_presences,
    :max_stage_video_channel_users,
    :max_video_channel_users,
    :mfa_level,
    :name,
    :nsfw,
    :nsfw_level,
    :owner_id,
    :preferred_locale,
    :premium_progress_bar_enabled,
    :premium_subscription_count,
    :premium_tier,
    :public_updates_channel_id,
    :region,
    :roles,
    :rules_channel_id,
    :safety_alerts_channel_id,
    :splash,
    :stickers,
    :system_channel_flags,
    :system_channel_id,
    :vanity_url_code,
    :verification_level,
    :widget_channel_id,
    :widget_enabled
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      afk_channel_id: {:union, [{:string, "snowflake"}, :null]},
      afk_timeout: {:integer, "int32"},
      application_id: {:union, [{:string, "snowflake"}, :null]},
      banner: {:union, [:string, :null]},
      default_message_notifications: {:integer, "int32"},
      description: {:union, [:string, :null]},
      discovery_splash: {:union, [:string, :null]},
      emojis: [{Discord.EmojiResponse, :t}],
      explicit_content_filter: {:integer, "int32"},
      features: [:string],
      home_header: {:union, [:string, :null]},
      icon: {:union, [:string, :null]},
      id: {:string, "snowflake"},
      max_members: {:union, [{:integer, "int32"}, :null]},
      max_presences: {:union, [{:integer, "int32"}, :null]},
      max_stage_video_channel_users: {:union, [{:integer, "int32"}, :null]},
      max_video_channel_users: {:union, [{:integer, "int32"}, :null]},
      mfa_level: {:integer, "int32"},
      name: :string,
      nsfw: :boolean,
      nsfw_level: {:integer, "int32"},
      owner_id: {:string, "snowflake"},
      preferred_locale: :string,
      premium_progress_bar_enabled: :boolean,
      premium_subscription_count: {:integer, "int32"},
      premium_tier: {:integer, "int32"},
      public_updates_channel_id: {:union, [{:string, "snowflake"}, :null]},
      region: :string,
      roles: [{Discord.GuildRoleResponse, :t}],
      rules_channel_id: {:union, [{:string, "snowflake"}, :null]},
      safety_alerts_channel_id: {:union, [{:string, "snowflake"}, :null]},
      splash: {:union, [:string, :null]},
      stickers: [{Discord.GuildStickerResponse, :t}],
      system_channel_flags: {:integer, "int32"},
      system_channel_id: {:union, [{:string, "snowflake"}, :null]},
      vanity_url_code: {:union, [:string, :null]},
      verification_level: {:integer, "int32"},
      widget_channel_id: {:union, [{:string, "snowflake"}, :null]},
      widget_enabled: :boolean
    ]
  end
end
