defmodule Mollie.ClientLinksAPI do
  @moduledoc """
  Provides API endpoint related to client links api
  """

  @default_client Mollie.Client

  @doc """
  Create client link

  Link a new or existing organization to your OAuth application, in effect creating a new client. The response
  contains a `clientLink` where you should redirect your customer to.

  ## Redirecting the Customer

  The `clientLink` URL behaves similarly to a standard OAuth authorization URL. Therefore, after receiving the
  `clientLink` URL in the API response, you need to **append the following query parameters** *before* redirecting
  the customer:

  * `client_id` _string (required)_

    The client ID you received when you registered your OAuth app. The ID starts with `app_`. For example:
    `app_abc123qwerty`.

  * `state` _string (required)_

    A random string **generated by your app** to prevent CSRF attacks. This will be reflected in the `state` query
    parameter when the user returns to the `redirect_uri` after authorizing your app.

  * `scope` _string (required)_

    A space-separated list of permissions ('scopes') your app requires. See the
    [permissions list](https://docs.mollie.com/docs/connect-permissions) for more information about the available
    scopes.

    We recommend at least : `onboarding.read onboarding.write`

  * `approval_prompt` _string_

    Can be set to `force` to force showing the consent screen to the merchant, *even when it is not necessary*. If you
    force an approval prompt and the user creates a new authorization, previously active authorizations will be
    revoked.

    Possible values: `auto` `force` (default: `auto`)

  ### Example of a Complete Redirect URL

  After adding the above url parameter your URL will look something like this and you can redirect your client to this
  page:

  ```
  https://my.mollie.com/dashboard/client-link/{id}?client_id={your_client_id}&state={unique_state}&scope=onboarding.read%20onboarding.write
  ```

  ## Error Handling

  Error handling is also dealt with similar to the [Authorize](https://docs.mollie.com/reference/authorize) endpoint:
  the customer is redirected back to your app's redirect URL with the `error` and `error_description` parameters added
  to the URL.

  > 🚧
  >
  > A client link must be used within 30 days of creation. After that period, it will expire and you will need to create a new client link.

  ## Request Body

  **Content Types**: `application/json`
  """
  @spec create_client_link(body :: Mollie.ClientLinkRequest.t(), opts :: keyword) ::
          {:ok, Mollie.ClientLinkResponse.t()} | {:error, Mollie.ErrorResponse.t()}
  def create_client_link(body, opts \\ []) do
    client = opts[:client] || @default_client

    client.request(%{
      args: [body: body],
      call: {Mollie.ClientLinksAPI, :create_client_link},
      url: "/client-links",
      body: body,
      method: :post,
      request: [{"application/json", {Mollie.ClientLinkRequest, :t}}],
      response: [
        {201, {Mollie.ClientLinkResponse, :t}},
        {404, {Mollie.ErrorResponse, :t}},
        {422, {Mollie.ErrorResponse, :t}}
      ],
      opts: opts
    })
  end
end
