defmodule Mollie.PaymentResponseDetails do
  @moduledoc """
  Provides struct and type for a PaymentResponseDetails
  """

  @type t :: %__MODULE__{
          bankAccount: String.t() | nil,
          bankBic: String.t() | nil,
          bankName: String.t() | nil,
          bankReason: String.t() | nil,
          bankReasonCode: String.t() | nil,
          batchReference: String.t() | nil,
          card3dsEci: String.t() | nil,
          cardAudition: String.t() | nil,
          cardBin: String.t() | nil,
          cardCountryCode: String.t() | nil,
          cardExpiryDate: String.t() | nil,
          cardFingerprint: String.t() | nil,
          cardFunding: String.t() | nil,
          cardHolder: String.t() | nil,
          cardIssuer: String.t() | nil,
          cardLabel: String.t() | nil,
          cardMaskedNumber: String.t() | nil,
          cardNumber: String.t() | nil,
          cardSecurity: String.t() | nil,
          consumerAccount: String.t() | nil,
          consumerBic: String.t() | nil,
          consumerName: String.t() | nil,
          creditorIdentifier: String.t() | nil,
          customerReference: String.t() | nil,
          dueDate: Date.t() | nil,
          endToEndIdentifier: String.t() | nil,
          failureMessage: String.t() | nil,
          failureReason: String.t() | nil,
          feeRegion: String.t() | nil,
          fileReference: String.t() | nil,
          giftcards: [map] | nil,
          issuer: String.t() | nil,
          mandateReference: String.t() | nil,
          maskedNumber: String.t() | nil,
          multibancoEntity: String.t() | nil,
          multibancoReference: String.t() | nil,
          paypalFee: Mollie.AmountNullable.t() | nil,
          paypalPayerId: String.t() | nil,
          paypalReference: String.t() | nil,
          qrCode: Mollie.PaymentResponseDetailsQrCode.t() | nil,
          receipt: Mollie.PaymentResponseDetailsReceipt.t() | nil,
          remainderAmount: Mollie.Amount.t() | nil,
          remainderDetails: map | nil,
          remainderMethod: String.t() | nil,
          sellerProtection: String.t() | nil,
          shippingAddress: map | nil,
          signatureDate: Date.t() | nil,
          terminalId: String.t() | nil,
          transferReference: String.t() | nil,
          voucherNumber: String.t() | nil,
          vouchers: [map] | nil,
          wallet: String.t() | nil
        }

  defstruct [
    :bankAccount,
    :bankBic,
    :bankName,
    :bankReason,
    :bankReasonCode,
    :batchReference,
    :card3dsEci,
    :cardAudition,
    :cardBin,
    :cardCountryCode,
    :cardExpiryDate,
    :cardFingerprint,
    :cardFunding,
    :cardHolder,
    :cardIssuer,
    :cardLabel,
    :cardMaskedNumber,
    :cardNumber,
    :cardSecurity,
    :consumerAccount,
    :consumerBic,
    :consumerName,
    :creditorIdentifier,
    :customerReference,
    :dueDate,
    :endToEndIdentifier,
    :failureMessage,
    :failureReason,
    :feeRegion,
    :fileReference,
    :giftcards,
    :issuer,
    :mandateReference,
    :maskedNumber,
    :multibancoEntity,
    :multibancoReference,
    :paypalFee,
    :paypalPayerId,
    :paypalReference,
    :qrCode,
    :receipt,
    :remainderAmount,
    :remainderDetails,
    :remainderMethod,
    :sellerProtection,
    :shippingAddress,
    :signatureDate,
    :terminalId,
    :transferReference,
    :voucherNumber,
    :vouchers,
    :wallet
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      bankAccount: :string,
      bankBic: :string,
      bankName: :string,
      bankReason: {:union, [:string, :null]},
      bankReasonCode: {:union, [:string, :null]},
      batchReference: {:union, [:string, :null]},
      card3dsEci: {:union, [:string, :null]},
      cardAudition: {:enum, ["consumer", "business"]},
      cardBin: {:union, [:string, :null]},
      cardCountryCode: {:union, [:string, :null]},
      cardExpiryDate: {:union, [:string, :null]},
      cardFingerprint: {:union, [:string, :null]},
      cardFunding: {:enum, ["debit", "credit", "prepaid", "deferred-debit"]},
      cardHolder: {:union, [:string, :null]},
      cardIssuer: {:union, [:string, :null]},
      cardLabel:
        {:enum,
         [
           "American Express",
           "Carta Si",
           "Carte Bleue",
           "Dankort",
           "Diners Club",
           "Discover",
           "JCB",
           "Laser",
           "Maestro",
           "Mastercard",
           "Unionpay",
           "Visa",
           "Vpay"
         ]},
      cardMaskedNumber: {:union, [:string, :null]},
      cardNumber: {:union, [:string, :null]},
      cardSecurity: {:enum, ["normal", "3dsecure"]},
      consumerAccount: {:union, [:string, :null]},
      consumerBic: {:union, [:string, :null]},
      consumerName: {:union, [:string, :null]},
      creditorIdentifier: {:union, [:string, :null]},
      customerReference: :string,
      dueDate: {:union, [{:string, "date"}, :null]},
      endToEndIdentifier: {:union, [:string, :null]},
      failureMessage: {:union, [:string, :null]},
      failureReason:
        {:enum,
         [
           "authentication_abandoned",
           "authentication_failed",
           "authentication_required",
           "authentication_unavailable_acs",
           "card_declined",
           "card_expired",
           "inactive_card",
           "insufficient_funds",
           "invalid_cvv",
           "invalid_card_holder_name",
           "invalid_card_number",
           "invalid_card_type",
           "possible_fraud",
           "refused_by_issuer",
           "unknown_reason"
         ]},
      feeRegion:
        {:enum,
         [
           "american-express",
           "amex-intra-eea",
           "carte-bancaire",
           "intra-eu",
           "intra-eu-corporate",
           "domestic",
           "maestro",
           "other",
           "inter",
           "intra_eea"
         ]},
      fileReference: {:union, [:string, :null]},
      giftcards: [:map],
      issuer: :string,
      mandateReference: {:union, [:string, :null]},
      maskedNumber: {:union, [:string, :null]},
      multibancoEntity: {:union, [:string, :null]},
      multibancoReference: {:union, [:string, :null]},
      paypalFee: {:union, [{Mollie.AmountNullable, :t}, :null]},
      paypalPayerId: {:union, [:string, :null]},
      paypalReference: {:union, [:string, :null]},
      qrCode: {Mollie.PaymentResponseDetailsQrCode, :t},
      receipt: {Mollie.PaymentResponseDetailsReceipt, :t},
      remainderAmount: {Mollie.Amount, :t},
      remainderDetails: :map,
      remainderMethod: :string,
      sellerProtection:
        {:enum,
         [
           "Eligible",
           "Ineligible",
           "Partially Eligible - INR Only",
           "Partially Eligible - Unauth Only",
           "Partially Eligible",
           "None",
           "Active",
           "Fraud Control - Unauth Premium Eligible"
         ]},
      shippingAddress: {:union, [:map, :null]},
      signatureDate: {:union, [{:string, "date"}, :null]},
      terminalId: :string,
      transferReference: {:union, [:string, :null]},
      voucherNumber: :string,
      vouchers: [:map],
      wallet: {:const, "applepay"}
    ]
  end
end
