defmodule Mollie.PaymentRequest do
  @moduledoc """
  Provides struct and type for a PaymentRequest
  """

  @type t :: %__MODULE__{
          _links: Mollie.PaymentRequestLinks.t() | nil,
          amount: Mollie.Amount.t() | nil,
          amountCaptured: Mollie.PaymentRequestAmountCaptured.t() | nil,
          amountChargedBack: Mollie.PaymentRequestAmountChargedBack.t() | nil,
          amountRefunded: Mollie.PaymentRequestAmountRefunded.t() | nil,
          amountRemaining: Mollie.PaymentRequestAmountRemaining.t() | nil,
          applePayPaymentToken: String.t() | nil,
          applicationFee: Mollie.PaymentRequestApplicationFee.t() | nil,
          authorizedAt: String.t() | nil,
          billingAddress: Mollie.PaymentRequestBillingAddress.t() | nil,
          cancelUrl: String.t() | nil,
          canceledAt: String.t() | nil,
          captureBefore: String.t() | nil,
          captureDelay: String.t() | nil,
          captureMode: String.t() | nil,
          cardToken: String.t() | nil,
          company: Mollie.PaymentRequestCompany.t() | nil,
          consumerDateOfBirth: Date.t() | nil,
          countryCode: String.t() | nil,
          createdAt: String.t() | nil,
          customerId: String.t() | nil,
          customerReference: String.t() | nil,
          description: String.t() | nil,
          details: Mollie.PaymentRequestDetails.t() | nil,
          digitalGoods: boolean | nil,
          dueDate: String.t() | nil,
          expiredAt: String.t() | nil,
          expiresAt: String.t() | nil,
          extraMerchantData: map | nil,
          failedAt: String.t() | nil,
          id: Mollie.PaymentRequestId.t() | nil,
          isCancelable: boolean | nil,
          issuer: String.t() | nil,
          lines: [map] | nil,
          locale: String.t() | nil,
          mandateId: String.t() | nil,
          metadata: map | String.t() | [String.t()] | nil,
          method: String.t() | nil,
          mode: String.t() | nil,
          orderId: String.t() | nil,
          paidAt: String.t() | nil,
          profileId: String.t() | nil,
          redirectUrl: String.t() | nil,
          resource: String.t() | nil,
          restrictPaymentMethodsToCountry: String.t() | nil,
          routing: [map] | nil,
          sequenceType: String.t() | nil,
          sessionId: String.t() | nil,
          settlementAmount: Mollie.PaymentRequestSettlementAmount.t() | nil,
          settlementId: String.t() | nil,
          shippingAddress: Mollie.PaymentAddress.t() | nil,
          status: Mollie.PaymentRequestStatus.t() | nil,
          statusReason: Mollie.StatusReason.t() | nil,
          subscriptionId: String.t() | nil,
          terminalId: String.t() | nil,
          testmode: boolean | nil,
          voucherNumber: String.t() | nil,
          voucherPin: String.t() | nil,
          webhookUrl: String.t() | nil
        }

  defstruct [
    :_links,
    :amount,
    :amountCaptured,
    :amountChargedBack,
    :amountRefunded,
    :amountRemaining,
    :applePayPaymentToken,
    :applicationFee,
    :authorizedAt,
    :billingAddress,
    :cancelUrl,
    :canceledAt,
    :captureBefore,
    :captureDelay,
    :captureMode,
    :cardToken,
    :company,
    :consumerDateOfBirth,
    :countryCode,
    :createdAt,
    :customerId,
    :customerReference,
    :description,
    :details,
    :digitalGoods,
    :dueDate,
    :expiredAt,
    :expiresAt,
    :extraMerchantData,
    :failedAt,
    :id,
    :isCancelable,
    :issuer,
    :lines,
    :locale,
    :mandateId,
    :metadata,
    :method,
    :mode,
    :orderId,
    :paidAt,
    :profileId,
    :redirectUrl,
    :resource,
    :restrictPaymentMethodsToCountry,
    :routing,
    :sequenceType,
    :sessionId,
    :settlementAmount,
    :settlementId,
    :shippingAddress,
    :status,
    :statusReason,
    :subscriptionId,
    :terminalId,
    :testmode,
    :voucherNumber,
    :voucherPin,
    :webhookUrl
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      _links: {Mollie.PaymentRequestLinks, :t},
      amount: {Mollie.Amount, :t},
      amountCaptured: {Mollie.PaymentRequestAmountCaptured, :t},
      amountChargedBack: {Mollie.PaymentRequestAmountChargedBack, :t},
      amountRefunded: {Mollie.PaymentRequestAmountRefunded, :t},
      amountRemaining: {Mollie.PaymentRequestAmountRemaining, :t},
      applePayPaymentToken: {:string, :generic},
      applicationFee: {:union, [{Mollie.PaymentRequestApplicationFee, :t}, :null]},
      authorizedAt: {:union, [{:string, :generic}, :null]},
      billingAddress: {Mollie.PaymentRequestBillingAddress, :t},
      cancelUrl: {:union, [{:string, :generic}, :null]},
      canceledAt: {:union, [{:string, :generic}, :null]},
      captureBefore: {:union, [{:string, :generic}, :null]},
      captureDelay: {:union, [{:string, :generic}, :null]},
      captureMode: {:enum, ["automatic", "manual"]},
      cardToken: {:string, :generic},
      company: {Mollie.PaymentRequestCompany, :t},
      consumerDateOfBirth: {:string, :date},
      countryCode: {:union, [{:string, :generic}, :null]},
      createdAt: {:string, :generic},
      customerId: {:string, :generic},
      customerReference: {:string, :generic},
      description: {:string, :generic},
      details: {:union, [{Mollie.PaymentRequestDetails, :t}, :null]},
      digitalGoods: :boolean,
      dueDate: {:string, :generic},
      expiredAt: {:union, [{:string, :generic}, :null]},
      expiresAt: {:union, [{:string, :generic}, :null]},
      extraMerchantData: :map,
      failedAt: {:union, [{:string, :generic}, :null]},
      id: {Mollie.PaymentRequestId, :t},
      isCancelable: {:union, [:boolean, :null]},
      issuer: {:union, [{:string, :generic}, :null]},
      lines: {:union, [[:map], :null]},
      locale:
        {:enum,
         [
           "en_US",
           "en_GB",
           "nl_NL",
           "nl_BE",
           "de_DE",
           "de_AT",
           "de_CH",
           "fr_FR",
           "fr_BE",
           "es_ES",
           "ca_ES",
           "pt_PT",
           "it_IT",
           "nb_NO",
           "sv_SE",
           "fi_FI",
           "da_DK",
           "is_IS",
           "hu_HU",
           "pl_PL",
           "lv_LV",
           "lt_LT",
           "null"
         ]},
      mandateId: {:union, [{:string, :generic}, :null]},
      metadata: {:union, [:map, {:string, :generic}, [string: :generic], :null]},
      method:
        {:enum,
         [
           "alma",
           "applepay",
           "bacs",
           "bancomatpay",
           "bancontact",
           "banktransfer",
           "belfius",
           "billie",
           "bizum",
           "blik",
           "creditcard",
           "directdebit",
           "eps",
           "giftcard",
           "ideal",
           "in3",
           "kbc",
           "klarna",
           "mbway",
           "mobilepay",
           "multibanco",
           "mybank",
           "paybybank",
           "payconiq",
           "paypal",
           "paysafecard",
           "pointofsale",
           "przelewy24",
           "riverty",
           "satispay",
           "swish",
           "trustly",
           "twint",
           "vipps",
           "voucher"
         ]},
      mode: {:enum, ["live", "test"]},
      orderId: {:union, [{:string, :generic}, :null]},
      paidAt: {:union, [{:string, :generic}, :null]},
      profileId: {:string, :generic},
      redirectUrl: {:union, [{:string, :generic}, :null]},
      resource: {:string, :generic},
      restrictPaymentMethodsToCountry: {:union, [{:string, :generic}, :null]},
      routing: {:union, [[:map], :null]},
      sequenceType: {:enum, ["oneoff", "first", "recurring"]},
      sessionId: {:string, :generic},
      settlementAmount: {Mollie.PaymentRequestSettlementAmount, :t},
      settlementId: {:union, [{:string, :generic}, :null]},
      shippingAddress: {Mollie.PaymentAddress, :t},
      status: {Mollie.PaymentRequestStatus, :t},
      statusReason: {:union, [{Mollie.StatusReason, :t}, :null]},
      subscriptionId: {:union, [{:string, :generic}, :null]},
      terminalId: {:string, :generic},
      testmode: {:union, [:boolean, :null]},
      voucherNumber: {:string, :generic},
      voucherPin: {:string, :generic},
      webhookUrl: {:union, [{:string, :generic}, :null]}
    ]
  end
end
