defmodule Mollie.PaymentResponse do
  @moduledoc """
  Provides struct and type for a PaymentResponse
  """

  @type t :: %__MODULE__{
          _links: Mollie.PaymentResponseLinks.t() | nil,
          amount: Mollie.Amount.t() | nil,
          amountCaptured: Mollie.PaymentResponseAmountCaptured.t() | nil,
          amountChargedBack: Mollie.PaymentResponseAmountChargedBack.t() | nil,
          amountRefunded: Mollie.PaymentResponseAmountRefunded.t() | nil,
          amountRemaining: Mollie.PaymentResponseAmountRemaining.t() | nil,
          applicationFee: Mollie.PaymentResponseApplicationFee.t() | nil,
          authorizedAt: String.t() | nil,
          billingAddress: Mollie.PaymentResponseBillingAddress.t() | nil,
          cancelUrl: String.t() | nil,
          canceledAt: String.t() | nil,
          captureBefore: String.t() | nil,
          captureDelay: String.t() | nil,
          captureMode: String.t() | nil,
          countryCode: String.t() | nil,
          createdAt: String.t() | nil,
          customerId: String.t() | nil,
          description: String.t() | nil,
          details: Mollie.PaymentResponseDetails.t() | nil,
          dueDate: String.t() | nil,
          expiredAt: String.t() | nil,
          expiresAt: String.t() | nil,
          failedAt: String.t() | nil,
          id: Mollie.PaymentResponseId.t() | nil,
          isCancelable: boolean | nil,
          issuer: String.t() | nil,
          lines: [map] | nil,
          locale: String.t() | nil,
          mandateId: String.t() | nil,
          metadata: map | String.t() | [String.t()] | nil,
          method: String.t() | nil,
          mode: String.t() | nil,
          orderId: String.t() | nil,
          paidAt: String.t() | nil,
          profileId: String.t() | nil,
          redirectUrl: String.t() | nil,
          resource: String.t() | nil,
          restrictPaymentMethodsToCountry: String.t() | nil,
          routing: [map] | nil,
          sequenceType: String.t() | nil,
          settlementAmount: Mollie.PaymentResponseSettlementAmount.t() | nil,
          settlementId: String.t() | nil,
          shippingAddress: Mollie.PaymentAddress.t() | nil,
          status: Mollie.PaymentResponseStatus.t() | nil,
          statusReason: Mollie.StatusReason.t() | nil,
          subscriptionId: String.t() | nil,
          testmode: boolean | nil,
          webhookUrl: String.t() | nil
        }

  defstruct [
    :_links,
    :amount,
    :amountCaptured,
    :amountChargedBack,
    :amountRefunded,
    :amountRemaining,
    :applicationFee,
    :authorizedAt,
    :billingAddress,
    :cancelUrl,
    :canceledAt,
    :captureBefore,
    :captureDelay,
    :captureMode,
    :countryCode,
    :createdAt,
    :customerId,
    :description,
    :details,
    :dueDate,
    :expiredAt,
    :expiresAt,
    :failedAt,
    :id,
    :isCancelable,
    :issuer,
    :lines,
    :locale,
    :mandateId,
    :metadata,
    :method,
    :mode,
    :orderId,
    :paidAt,
    :profileId,
    :redirectUrl,
    :resource,
    :restrictPaymentMethodsToCountry,
    :routing,
    :sequenceType,
    :settlementAmount,
    :settlementId,
    :shippingAddress,
    :status,
    :statusReason,
    :subscriptionId,
    :testmode,
    :webhookUrl
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      _links: {Mollie.PaymentResponseLinks, :t},
      amount: {Mollie.Amount, :t},
      amountCaptured: {Mollie.PaymentResponseAmountCaptured, :t},
      amountChargedBack: {Mollie.PaymentResponseAmountChargedBack, :t},
      amountRefunded: {Mollie.PaymentResponseAmountRefunded, :t},
      amountRemaining: {Mollie.PaymentResponseAmountRemaining, :t},
      applicationFee: {:union, [{Mollie.PaymentResponseApplicationFee, :t}, :null]},
      authorizedAt: {:union, [:string, :null]},
      billingAddress: {Mollie.PaymentResponseBillingAddress, :t},
      cancelUrl: {:union, [:string, :null]},
      canceledAt: {:union, [:string, :null]},
      captureBefore: {:union, [:string, :null]},
      captureDelay: {:union, [:string, :null]},
      captureMode: {:enum, ["automatic", "manual"]},
      countryCode: {:union, [:string, :null]},
      createdAt: :string,
      customerId: :string,
      description: :string,
      details: {:union, [{Mollie.PaymentResponseDetails, :t}, :null]},
      dueDate: :string,
      expiredAt: {:union, [:string, :null]},
      expiresAt: {:union, [:string, :null]},
      failedAt: {:union, [:string, :null]},
      id: {Mollie.PaymentResponseId, :t},
      isCancelable: {:union, [:boolean, :null]},
      issuer: {:union, [:string, :null]},
      lines: {:union, [[:map], :null]},
      locale:
        {:enum,
         [
           "en_US",
           "en_GB",
           "nl_NL",
           "nl_BE",
           "de_DE",
           "de_AT",
           "de_CH",
           "fr_FR",
           "fr_BE",
           "es_ES",
           "ca_ES",
           "pt_PT",
           "it_IT",
           "nb_NO",
           "sv_SE",
           "fi_FI",
           "da_DK",
           "is_IS",
           "hu_HU",
           "pl_PL",
           "lv_LV",
           "lt_LT",
           "null"
         ]},
      mandateId: {:union, [:string, :null]},
      metadata: {:union, [:map, :string, [:string], :null]},
      method:
        {:enum,
         [
           "alma",
           "applepay",
           "bacs",
           "bancomatpay",
           "bancontact",
           "banktransfer",
           "belfius",
           "billie",
           "bizum",
           "blik",
           "creditcard",
           "directdebit",
           "eps",
           "giftcard",
           "ideal",
           "in3",
           "kbc",
           "klarna",
           "mbway",
           "mobilepay",
           "multibanco",
           "mybank",
           "paybybank",
           "payconiq",
           "paypal",
           "paysafecard",
           "pointofsale",
           "przelewy24",
           "riverty",
           "satispay",
           "swish",
           "trustly",
           "twint",
           "vipps",
           "voucher",
           "klarnapaylater",
           "klarnapaynow",
           "klarnasliceit"
         ]},
      mode: {:enum, ["live", "test"]},
      orderId: {:union, [:string, :null]},
      paidAt: {:union, [:string, :null]},
      profileId: :string,
      redirectUrl: {:union, [:string, :null]},
      resource: :string,
      restrictPaymentMethodsToCountry: {:union, [:string, :null]},
      routing: {:union, [[:map], :null]},
      sequenceType: {:enum, ["oneoff", "first", "recurring"]},
      settlementAmount: {Mollie.PaymentResponseSettlementAmount, :t},
      settlementId: {:union, [:string, :null]},
      shippingAddress: {Mollie.PaymentAddress, :t},
      status: {Mollie.PaymentResponseStatus, :t},
      statusReason: {:union, [{Mollie.StatusReason, :t}, :null]},
      subscriptionId: {:union, [:string, :null]},
      testmode: {:union, [:boolean, :null]},
      webhookUrl: {:union, [:string, :null]}
    ]
  end
end
