defmodule Affinda.DocumentMeta do
  @moduledoc """
  Provides struct and type for a DocumentMeta
  """

  @type t :: %__MODULE__{
          archivedDt: DateTime.t() | nil,
          childDocuments: [Affinda.DocumentMetaChildDocuments.t()] | nil,
          collection: Affinda.DocumentMetaCollection.t() | nil,
          confirmedBy: Affinda.UserNullable.t() | nil,
          confirmedDt: DateTime.t() | nil,
          createdBy: Affinda.User.t() | nil,
          createdDt: DateTime.t() | nil,
          customIdentifier: String.t() | nil,
          errorCode: String.t() | nil,
          errorDetail: String.t() | nil,
          expiryTime: DateTime.t() | nil,
          failed: boolean | nil,
          file: String.t() | nil,
          fileName: String.t() | nil,
          identifier: String.t(),
          isArchived: boolean | nil,
          isConfirmed: boolean | nil,
          isOcrd: boolean | nil,
          isRejected: boolean | nil,
          language: String.t() | nil,
          ocrConfidence: number | nil,
          pages: [Affinda.PageMeta.t()],
          parentDocument: Affinda.DocumentMetaParentDocument.t() | nil,
          pdf: String.t() | nil,
          ready: boolean | nil,
          readyDt: DateTime.t() | nil,
          regionBias: Affinda.RegionBias.t() | nil,
          rejectedBy: Affinda.UserNullable.t() | nil,
          rejectedDt: DateTime.t() | nil,
          reviewUrl: String.t() | nil,
          skipParse: boolean | nil,
          sourceEmail: String.t() | nil,
          sourceEmailAddress: String.t() | nil,
          tags: [Affinda.Tag.t()] | nil,
          workspace: Affinda.DocumentMetaWorkspace.t()
        }

  defstruct [
    :archivedDt,
    :childDocuments,
    :collection,
    :confirmedBy,
    :confirmedDt,
    :createdBy,
    :createdDt,
    :customIdentifier,
    :errorCode,
    :errorDetail,
    :expiryTime,
    :failed,
    :file,
    :fileName,
    :identifier,
    :isArchived,
    :isConfirmed,
    :isOcrd,
    :isRejected,
    :language,
    :ocrConfidence,
    :pages,
    :parentDocument,
    :pdf,
    :ready,
    :readyDt,
    :regionBias,
    :rejectedBy,
    :rejectedDt,
    :reviewUrl,
    :skipParse,
    :sourceEmail,
    :sourceEmailAddress,
    :tags,
    :workspace
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      archivedDt: {:string, "date-time"},
      childDocuments: [{Affinda.DocumentMetaChildDocuments, :t}],
      collection: {Affinda.DocumentMetaCollection, :t},
      confirmedBy: {Affinda.UserNullable, :t},
      confirmedDt: {:string, "date-time"},
      createdBy: {Affinda.User, :t},
      createdDt: {:string, "date-time"},
      customIdentifier: :string,
      errorCode: :string,
      errorDetail: :string,
      expiryTime: {:string, "date-time"},
      failed: :boolean,
      file: :string,
      fileName: :string,
      identifier: :string,
      isArchived: :boolean,
      isConfirmed: :boolean,
      isOcrd: :boolean,
      isRejected: :boolean,
      language: :string,
      ocrConfidence: :number,
      pages: [{Affinda.PageMeta, :t}],
      parentDocument: {Affinda.DocumentMetaParentDocument, :t},
      pdf: :string,
      ready: :boolean,
      readyDt: {:string, "date-time"},
      regionBias: {Affinda.RegionBias, :t},
      rejectedBy: {Affinda.UserNullable, :t},
      rejectedDt: {:string, "date-time"},
      reviewUrl: :string,
      skipParse: :boolean,
      sourceEmail: :string,
      sourceEmailAddress: :string,
      tags: [{Affinda.Tag, :t}],
      workspace: {Affinda.DocumentMetaWorkspace, :t}
    ]
  end
end
