defmodule ResumeData do
  @moduledoc """
  Provides struct and type for a ResumeData
  """

  @type t :: %__MODULE__{
          certifications: [String.t()] | nil,
          dateOfBirth: String.t() | nil,
          education: [Education.t()] | nil,
          emails: [String.t()] | nil,
          headShot: String.t() | nil,
          isResumeProbability: integer | nil,
          languageCodes: [String.t()] | nil,
          languages: [String.t()] | nil,
          linkedin: String.t() | nil,
          location: Location.t() | nil,
          name: ResumeDataName.t() | nil,
          objective: String.t() | nil,
          phoneNumberDetails: [ResumeDataPhoneNumberDetails.t()] | nil,
          phoneNumbers: [String.t()] | nil,
          profession: String.t() | nil,
          publications: [String.t()] | nil,
          rawText: String.t() | nil,
          redactedText: String.t() | nil,
          referees: [ResumeDataReferees.t()] | nil,
          sections: [ResumeDataSections.t()] | nil,
          skills: [ResumeDataSkills.t()] | nil,
          summary: String.t() | nil,
          totalYearsExperience: integer | nil,
          websites: [String.t()] | nil,
          workExperience: [ResumeDataWorkExperience.t()] | nil
        }

  defstruct [
    :certifications,
    :dateOfBirth,
    :education,
    :emails,
    :headShot,
    :isResumeProbability,
    :languageCodes,
    :languages,
    :linkedin,
    :location,
    :name,
    :objective,
    :phoneNumberDetails,
    :phoneNumbers,
    :profession,
    :publications,
    :rawText,
    :redactedText,
    :referees,
    :sections,
    :skills,
    :summary,
    :totalYearsExperience,
    :websites,
    :workExperience
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      certifications: [string: :generic],
      dateOfBirth: {:string, :generic},
      education: [{Education, :t}],
      emails: [string: :email],
      headShot: {:string, :generic},
      isResumeProbability: :integer,
      languageCodes: [string: :generic],
      languages: [
        enum: [
          "Ainu",
          "Akan",
          "Akkadian",
          "Amharic",
          "Anam",
          "Arabic",
          "Aramaic",
          "Arem",
          "Armenian",
          "Awadhi",
          "Aymara",
          "Azari",
          "Bagheli",
          "Bagri",
          "Bahasa",
          "Bambara",
          "Bangala",
          "Bardi",
          "Bassa",
          "Batak",
          "Belarusian",
          "Bemba",
          "Benga",
          "Bengali",
          "Berber",
          "Bhojpuri",
          "Bislama",
          "Brahui",
          "Bulgarian",
          "Bunu",
          "Cambodian",
          "Carew",
          "Carib",
          "Catalan",
          "Cebuano",
          "Chakma",
          "Chamorro",
          "Chango",
          "Chewa",
          "Croatian",
          "Czech",
          "Dagbani",
          "Danish",
          "Dari",
          "Dayi",
          "Dhatki",
          "Dhivehi",
          "Dinka",
          "Dogri",
          "Duala",
          "Dutch",
          "English",
          "Esperanto",
          "Estonian",
          "Ewondo",
          "Faroese",
          "Filipino",
          "Finnish",
          "Formula",
          "French",
          "Frisian",
          "Friulian",
          "Fula",
          "Gaelic",
          "Galo",
          "Garhwali",
          "Garifuna",
          "German",
          "Gikuyu",
          "Gujarati",
          "Gujerati",
          "Gwere",
          "Hawaiian",
          "Haya",
          "Hebrew",
          "Hindi",
          "Hmu",
          "Hokkien",
          "Hopi",
          "Hungarian",
          "Hup",
          "Ibanag",
          "Igbo",
          "Ilokano",
          "Indonesian",
          "Intermediate",
          "Irish",
          "Italian",
          "Japanese",
          "Jiba",
          "Kachin",
          "Kalenjin",
          "Kamayo",
          "Kannada",
          "Kaonde",
          "Kayan",
          "Khandeshi",
          "Khmer",
          "Kikuyu",
          "Kodava",
          "Koma",
          "Kongo",
          "Konkani",
          "Korean",
          "Korwa",
          "Kreyol",
          "Krio",
          "Kumaoni",
          "Kurdish",
          "Kurukh",
          "Kwa",
          "Ladino",
          "Lango",
          "Latvian",
          "Lawa",
          "Lingala",
          "Lithuanian",
          "Lule",
          "Luxembourgish",
          "Magahi",
          "Maithili",
          "Malay",
          "Malayalam",
          "Malaysian",
          "Malvi",
          "Maninka",
          "Manipuri",
          "Manx",
          "Marathi",
          "Mayan",
          "Medumba",
          "Memoni",
          "Mewari",
          "Mizo",
          "Montenegrin",
          "Mwan",
          "Mwanga",
          "Ndebele",
          "Nepali",
          "Nimadi",
          "Oriya",
          "Oromo",
          "Ovambo",
          "Pamona",
          "Pangasinan",
          "Pashto",
          "Phoenician",
          "Polish",
          "Portuguese",
          "Pulaar",
          "Pular",
          "Punjabi",
          "Quecha",
          "Rajasthani",
          "Romanian",
          "Russian",
          "Sakha",
          "Sango",
          "Santhali",
          "Saraiki",
          "Seim",
          "Shading",
          "Shama",
          "Shan",
          "Shona",
          "Silesian",
          "Sindhi",
          "Slovak",
          "Slovene",
          "Soga",
          "Sogdian",
          "Sotho",
          "Spanish",
          "Sudanese",
          "Sumerian",
          "Surajpuri",
          "Surigaonon",
          "Swati",
          "Swazi",
          "Swedish",
          "Tagalog",
          "Tamil",
          "Tausug",
          "Telugu",
          "Tetum",
          "Tharu",
          "Tibetan",
          "Tigrinya",
          "Tripuri",
          "Tswana",
          "Tulu",
          "Turkish",
          "Tuwali",
          "Ubi",
          "Ukrainian",
          "Urdu",
          "Veps",
          "Vietnamese",
          "Wagdi",
          "Waziri",
          "Xhosa",
          "Yiddish",
          "Yoruba"
        ]
      ],
      linkedin: {:string, :generic},
      location: {Location, :t},
      name: {ResumeDataName, :t},
      objective: {:string, :generic},
      phoneNumberDetails: [{ResumeDataPhoneNumberDetails, :t}],
      phoneNumbers: [string: :generic],
      profession: {:string, :generic},
      publications: [string: :generic],
      rawText: {:string, :generic},
      redactedText: {:string, :generic},
      referees: [{ResumeDataReferees, :t}],
      sections: [{ResumeDataSections, :t}],
      skills: [{ResumeDataSkills, :t}],
      summary: {:string, :generic},
      totalYearsExperience: :integer,
      websites: [string: :generic],
      workExperience: [{ResumeDataWorkExperience, :t}]
    ]
  end
end
