defmodule ResumeSearchParameters do
  @moduledoc """
  Provides struct and type for a ResumeSearchParameters
  """

  @type t :: %__MODULE__{
          customData: [ResumeSearchParametersCustomData.t()] | nil,
          degrees: [String.t()] | nil,
          degreesRequired: boolean | nil,
          educationWeight: number | nil,
          highestDegreeTypes: [String.t()] | nil,
          highestDegreeTypesRequired: boolean | nil,
          indices: [String.t()],
          institutions: [String.t()] | nil,
          institutionsRequired: boolean | nil,
          isCurrentStudent: boolean | nil,
          isCurrentStudentRequired: boolean | nil,
          isRecentGraduate: boolean | nil,
          isRecentGraduateRequired: boolean | nil,
          jobDescription: String.t() | nil,
          jobTitles: [String.t()] | nil,
          jobTitlesCurrentOnly: boolean | nil,
          jobTitlesRequired: boolean | nil,
          jobTitlesWeight: number | nil,
          languages: [ResumeSearchParametersSkill.t()] | nil,
          languagesWeight: number | nil,
          locations: [ResumeSearchParametersLocation.t()] | nil,
          locationsRequired: boolean | nil,
          locationsWeight: number | nil,
          managementLevel: String.t() | nil,
          managementLevelRequired: boolean | nil,
          managementLevelWeight: number | nil,
          resume: String.t() | nil,
          searchExpression: String.t() | nil,
          searchExpressionRequired: boolean | nil,
          searchExpressionWeight: number | nil,
          skills: [ResumeSearchParametersSkill.t()] | nil,
          skillsWeight: number | nil,
          socCodes: [integer] | nil,
          socCodesRequired: boolean | nil,
          socCodesWeight: number | nil,
          yearsExperienceMax: integer | nil,
          yearsExperienceMin: integer | nil,
          yearsExperienceRequired: boolean | nil,
          yearsExperienceWeight: number | nil
        }

  defstruct [
    :customData,
    :degrees,
    :degreesRequired,
    :educationWeight,
    :highestDegreeTypes,
    :highestDegreeTypesRequired,
    :indices,
    :institutions,
    :institutionsRequired,
    :isCurrentStudent,
    :isCurrentStudentRequired,
    :isRecentGraduate,
    :isRecentGraduateRequired,
    :jobDescription,
    :jobTitles,
    :jobTitlesCurrentOnly,
    :jobTitlesRequired,
    :jobTitlesWeight,
    :languages,
    :languagesWeight,
    :locations,
    :locationsRequired,
    :locationsWeight,
    :managementLevel,
    :managementLevelRequired,
    :managementLevelWeight,
    :resume,
    :searchExpression,
    :searchExpressionRequired,
    :searchExpressionWeight,
    :skills,
    :skillsWeight,
    :socCodes,
    :socCodesRequired,
    :socCodesWeight,
    :yearsExperienceMax,
    :yearsExperienceMin,
    :yearsExperienceRequired,
    :yearsExperienceWeight
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      customData: [{ResumeSearchParametersCustomData, :t}],
      degrees: [string: :generic],
      degreesRequired: :boolean,
      educationWeight: :number,
      highestDegreeTypes: [enum: ["school", "certificate", "bachelors", "masters", "doctoral"]],
      highestDegreeTypesRequired: :boolean,
      indices: [string: :generic],
      institutions: [string: :generic],
      institutionsRequired: :boolean,
      isCurrentStudent: :boolean,
      isCurrentStudentRequired: :boolean,
      isRecentGraduate: :boolean,
      isRecentGraduateRequired: :boolean,
      jobDescription: {:string, :generic},
      jobTitles: [string: :generic],
      jobTitlesCurrentOnly: :boolean,
      jobTitlesRequired: :boolean,
      jobTitlesWeight: :number,
      languages: [{ResumeSearchParametersSkill, :t}],
      languagesWeight: :number,
      locations: [{ResumeSearchParametersLocation, :t}],
      locationsRequired: :boolean,
      locationsWeight: :number,
      managementLevel: {:enum, ["None", "Low", "Mid", "Upper"]},
      managementLevelRequired: :boolean,
      managementLevelWeight: :number,
      resume: {:string, :generic},
      searchExpression: {:string, :generic},
      searchExpressionRequired: :boolean,
      searchExpressionWeight: :number,
      skills: [{ResumeSearchParametersSkill, :t}],
      skillsWeight: :number,
      socCodes: [:integer],
      socCodesRequired: :boolean,
      socCodesWeight: :number,
      yearsExperienceMax: :integer,
      yearsExperienceMin: :integer,
      yearsExperienceRequired: :boolean,
      yearsExperienceWeight: :number
    ]
  end
end
